# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

project 'Runner', {
  'Debug-dev' => :debug,
  'Profile-dev' => :release,
  'Release-dev' => :release,
  'Debug-prod' => :debug,
  'Profile-prod' => :release,
  'Release-prod' => :release,
}

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  if ENV['FLAVOR'] == 'dev'
    # Development-specific settings (e.g., Firebase dev plist)
  elsif ENV['FLAVOR'] == 'prod'
    # Production-specific settings (e.g., Firebase prod plist)
  end

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
